version: '3.8'

services:
  web:
    build:
      context: .  # Dockerfile이 위치한 폴더 경로
    volumes:
      - ./app:/app  # 로컬 app 디렉토리를 컨테이너의 /app에 마운트
    working_dir: /app  # 컨테이너의 기본 작업 디렉토리
    ports:
      - "8000:8000"  # 호스트의 8000번 포트를 컨테이너의 8000번 포트와 연결
    command: python manage.py runserver 0.0.0.0:8000  # Django 서버 실행 명령

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d  # Nginx 설정 파일
      - ./certs:/etc/nginx/certs  # 인증서 파일 경로
    ports:
      - "443:443"  # 호스트의 443번 포트를 컨테이너의 443번 포트와 연결
    depends_on:
      - web
