# Generated by Django 4.2.16 on 2024-12-12 05:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField(default=uuid.uuid4)),
                ("m_code", models.CharField(max_length=50)),
                ("no", models.IntegerField()),
                ("quiz_code", models.BigIntegerField()),
                ("answer", models.TextField()),
                ("correct", models.CharField(max_length=1)),
                ("cre_date", models.DateTimeField()),
            ],
        ),
    ]
