# Generated by Django 4.2.16 on 2025-01-08 07:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("m_code", models.CharField(db_index=True, max_length=50)),
                ("quiz_code", models.BigIntegerField(db_index=True)),
                ("correct", models.CharField(db_index=True, max_length=1)),
                ("cre_date", models.DateTimeField(db_index=True)),
                (
                    "f_mchapter_id",
                    models.BigIntegerField(db_index=True, default=14201897),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("date", models.DateField(db_index=True)),
                ("report_content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("user_id", "date")},
            },
        ),
    ]
