# Generated by Django 4.2.16 on 2024-12-16 02:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_testhistory_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testhistory",
            name="correct",
            field=models.CharField(db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name="testhistory",
            name="cre_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="testhistory",
            name="m_code",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="testhistory",
            name="quiz_code",
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="testhistory",
            name="user_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
