# Generated by Django 4.2.16 on 2024-12-16 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_testhistory_correct_alter_testhistory_cre_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("date", models.DateField(db_index=True)),
                ("report_content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("user_id", "date")},
            },
        ),
    ]
