# Generated by Django 4.2.16 on 2025-01-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                ("node_id", models.IntegerField(primary_key=True, serialize=False)),
                ("f_subject_id", models.IntegerField()),
                ("f_mchapter_nm", models.CharField(max_length=255)),
                ("f_lchapter_id", models.IntegerField()),
                ("f_lchapter_nm", models.CharField(max_length=255)),
                ("f_schapter_id", models.IntegerField()),
                ("f_schapter_nm", models.CharField(max_length=255)),
                ("f_tchapter_id", models.IntegerField()),
                ("f_tchapter_nm", models.CharField(max_length=255)),
                ("area", models.CharField(max_length=100)),
            ],
        ),
    ]
