# Generated by Django 4.2.16 on 2025-01-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_node"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="area",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="node",
            name="f_lchapter_id",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="node",
            name="f_lchapter_nm",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="node",
            name="f_mchapter_nm",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="node",
            name="f_schapter_id",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="node",
            name="f_schapter_nm",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="node",
            name="f_subject_id",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="node",
            name="f_tchapter_id",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="node",
            name="f_tchapter_nm",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="node",
            name="node_id",
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
