name: Django CI and Push to ECR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t ai-report .

    - name: Run Tests
      run: |
        docker run ai-report python manage.py test

  push-to-ecr:
    needs: build-and-test  # build-and-test가 성공해야 실행
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-northeast-2 \
        | docker login --username AWS --password-stdin 339712929315.dkr.ecr.ap-northeast-2.amazonaws.com
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Tag and Push Docker Image to ECR
      run: |
        IMAGE_TAG=$(git rev-parse --short HEAD)
        docker tag ai-report:latest 339712929315.dkr.ecr.ap-northeast-2.amazonaws.com/bigdata/team-01:$IMAGE_TAG
        docker push 339712929315.dkr.ecr.ap-northeast-2.amazonaws.com/bigdata/team-01:$IMAGE_TAG
