name: GKT API CI/CD

on:
  push:
    branches:
      - dev/GKT_API
env:
  ECR_REGISTRY: 339712929315.dkr.ecr.ap-northeast-2.amazonaws.com  # ECR 레지스트리
  ECR_REPOSITORY: bigdata/team-01/gkt-api  # ECR 저장소 이름

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: AWS Credential 인증
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t bigdata/team-01/gkt-api ML/GKT_API

    - name: Build and Push to ECR
      uses: docker/build-push-action@v5
      with:
        context: WEB
        file: WEB/Dockerfile
        push: true
        tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest