name: Lambda Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      s3_event:
        description: "S3 이벤트 데이터"
        required: false
        default: "{}"

jobs:
  lambda-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print S3 Event Data
        run: |
          echo "S3 Event Data:"
          echo "${{ github.event.inputs.s3_event }}"

      - name: Process Lambda Trigger
        run: |
          echo "Processing Lambda trigger..."
          echo "S3 Event Data:"
          echo "${{ github.event.inputs.s3_event }}"
          echo "Lambda workflow executed successfully."
