name: ML CI/CD Pipeline

# 워크플로 트리거 설정
on:
  push:
    branches:
      - main
  workflow_dispatch:  # API 호출을 통해 워크플로 트리거 가능

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print a message
        run: echo "ML CI/CD Pipeline Triggered via workflow_dispatch"
