name: Lambda Trigger Workflow

# 워크플로 트리거 설정
on:
  workflow_dispatch:  # Lambda에서 GitHub Actions 트리거 가능
    inputs:
      s3_event:
        description: "S3 이벤트 데이터"
        required: false
        default: "{}"  # 기본값으로 빈 JSON 데이터

jobs:
  lambda-trigger:
    runs-on: ubuntu-latest

    steps:
      # 코드를 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # S3 이벤트 데이터 출력 (디버깅용)
      - name: Print S3 Event Data
        run: echo "S3 Event Data: ${{ github.event.inputs.s3_event }}"

      # Lambda 연계 작업 실행
      - name: Process Lambda Trigger
        run: |
          echo "Processing Lambda trigger..."
          echo "S3 Event Data: ${{ github.event.inputs.s3_event }}"
          # 필요한 작업 또는 명령어 추가
          echo "Lambda workflow executed successfully."
